// <auto-generated />
using System;
using LteCar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LteCar.Server.Migrations
{
    [DbContext(typeof(LteCarContext))]
    [Migration("20250524151149_AddSetupFilterToDbSets")]
    partial class AddSetupFilterToDbSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelMapHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeesionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoStreamPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresAxis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarChannels");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadIntervalTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelemetryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarTelemetry");
                });

            modelBuilder.Entity("LteCar.Server.Data.SetupFilterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SetupFilterTypes");
                });

            modelBuilder.Entity("LteCar.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveVehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVehicleId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarSecret")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSetups");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CalibrationMax")
                        .HasColumnType("REAL");

                    b.Property<float>("CalibrationMin")
                        .HasColumnType("REAL");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAxis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserSetupId");

                    b.ToTable("UserSetupChannels");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Paramerters")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetupFilterTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetupFilterTypeId");

                    b.HasIndex("UserSetupId");

                    b.ToTable("UserSetupFilters");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilterSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilterTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleFunctionTargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelSourceId");

                    b.HasIndex("FilterSourceId");

                    b.HasIndex("FilterTargetId");

                    b.HasIndex("UserSetupId");

                    b.HasIndex("VehicleFunctionTargetId");

                    b.ToTable("UserSetupLinks");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarTelemetryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverrideTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarTelemetryId");

                    b.HasIndex("UserSetupId");

                    b.ToTable("UserSetupTelemetries");
                });

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.OwnsOne("LteCar.Onboard.VideoSettings", "VideoSettings", b1 =>
                        {
                            b1.Property<int>("CarId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Bitrate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VideoBitrate");

                            b1.Property<float?>("Brightness")
                                .HasColumnType("REAL")
                                .HasColumnName("VideoBrightness");

                            b1.Property<int?>("Framerate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VideoFramerate");

                            b1.Property<int?>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VideoHeight");

                            b1.Property<int?>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VideoWidth");

                            b1.HasKey("CarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.Navigation("VideoSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("LteCar.Server.Data.CarChannel", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany("Functions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarTelemetry", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("LteCar.Server.Data.User", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "ActiveVehicle")
                        .WithMany()
                        .HasForeignKey("ActiveVehicleId");

                    b.Navigation("ActiveVehicle");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupChannel", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany("UserSetupChannels")
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFilter", b =>
                {
                    b.HasOne("LteCar.Server.Data.SetupFilterType", "SetupFilterType")
                        .WithMany()
                        .HasForeignKey("SetupFilterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany("UserSetupFilters")
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetupFilterType");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupLink", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserSetupChannel", "ChannelSource")
                        .WithMany()
                        .HasForeignKey("ChannelSourceId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("LteCar.Server.Data.UserSetupFilter", "FilterSource")
                        .WithMany()
                        .HasForeignKey("FilterSourceId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("LteCar.Server.Data.UserSetupFilter", "FilterTarget")
                        .WithMany()
                        .HasForeignKey("FilterTargetId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany("UserSetupLinks")
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.CarChannel", "VehicleFunctionTarget")
                        .WithMany()
                        .HasForeignKey("VehicleFunctionTargetId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ChannelSource");

                    b.Navigation("FilterSource");

                    b.Navigation("FilterTarget");

                    b.Navigation("UserSetup");

                    b.Navigation("VehicleFunctionTarget");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetry", b =>
                {
                    b.HasOne("LteCar.Server.Data.CarTelemetry", "CarTelemetry")
                        .WithMany()
                        .HasForeignKey("CarTelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany()
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarTelemetry");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.Navigation("Functions");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.Navigation("UserSetupChannels");

                    b.Navigation("UserSetupFilters");

                    b.Navigation("UserSetupLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
