// <auto-generated />
using System;
using LteCar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LteCar.Server.Migrations
{
    [DbContext(typeof(LteCarContext))]
    [Migration("20251024192337_Cascadesssyyyy")]
    partial class Cascadesssyyyy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("UserSessionSeq");

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarIdentityKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChannelMapHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("VideoStreamPort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarIdentityKey")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresAxis")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarChannels");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadIntervalTicks")
                        .HasColumnType("int");

                    b.Property<string>("TelemetryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarTelemetry");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarVideoStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastStatusUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProcessArguments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreamPurpose")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Port");

                    b.HasIndex("CarId", "IsActive");

                    b.HasIndex("CarId", "StreamId")
                        .IsUnique();

                    b.ToTable("CarVideoStreams", (string)null);
                });

            modelBuilder.Entity("LteCar.Server.Data.SetupFilterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SetupFilterTypes");
                });

            modelBuilder.Entity("LteCar.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransferCode")
                        .HasMaxLength(6)
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TransferCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVehicleId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("TransferCode")
                        .IsUnique()
                        .HasFilter("[TransferCode] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CarSecret")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSetups");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<float?>("CalibrationMax")
                        .HasColumnType("real");

                    b.Property<float?>("CalibrationMin")
                        .HasColumnType("real");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAxis")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserChannelDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserChannelDeviceId", "IsAxis", "ChannelId")
                        .IsUnique();

                    b.ToTable("UserChannel");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannelDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceName")
                        .IsUnique();

                    b.ToTable("UserChannelDevice");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFlowNodeBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserSetupFlowNodes", (string)null);

                    b.HasDiscriminator<string>("NodeType").HasValue("UserSetupFlowNodeBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFunctionNodeParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParameterValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "ParameterName")
                        .IsUnique();

                    b.ToTable("UserSetupFunctionNodeParameter");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SourcePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserSetupFromNodeId")
                        .HasColumnType("int");

                    b.Property<int>("UserSetupToNodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSetupFromNodeId");

                    b.HasIndex("UserSetupToNodeId");

                    b.ToTable("UserSetupLink");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarTelemetryId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("OverrideTicks")
                        .HasColumnType("int");

                    b.Property<int>("UserSetupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarTelemetryId");

                    b.HasIndex("UserSetupId");

                    b.ToTable("UserSetupTelemetries");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupCarChannelNode", b =>
                {
                    b.HasBaseType("LteCar.Server.Data.UserSetupFlowNodeBase");

                    b.Property<int>("CarChannelId")
                        .HasColumnType("int");

                    b.HasIndex("CarChannelId");

                    b.HasIndex("UserSetupId");

                    b.HasDiscriminator().HasValue("C");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFunctionNode", b =>
                {
                    b.HasBaseType("LteCar.Server.Data.UserSetupFlowNodeBase");

                    b.Property<string>("SetupFunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("UserSetupId");

                    b.HasDiscriminator().HasValue("F");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetryNode", b =>
                {
                    b.HasBaseType("LteCar.Server.Data.UserSetupFlowNodeBase");

                    b.Property<int>("TelemetryId")
                        .HasColumnType("int");

                    b.HasIndex("TelemetryId");

                    b.HasIndex("UserSetupId");

                    b.HasDiscriminator().HasValue("UserSetupTelemetryNode");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupUserChannelNode", b =>
                {
                    b.HasBaseType("LteCar.Server.Data.UserSetupFlowNodeBase");

                    b.Property<int>("UserChannelId")
                        .HasColumnType("int");

                    b.HasIndex("UserChannelId");

                    b.HasIndex("UserSetupId");

                    b.HasDiscriminator().HasValue("U");
                });

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.OwnsOne("LteCar.Onboard.VideoSettings", "VideoSettings", b1 =>
                        {
                            b1.Property<int>("CarId")
                                .HasColumnType("int");

                            b1.Property<int?>("Bitrate")
                                .HasColumnType("int")
                                .HasColumnName("VideoBitrate");

                            b1.Property<float?>("Brightness")
                                .HasColumnType("real")
                                .HasColumnName("VideoBrightness");

                            b1.Property<int?>("Framerate")
                                .HasColumnType("int")
                                .HasColumnName("VideoFramerate");

                            b1.Property<int?>("Height")
                                .HasColumnType("int")
                                .HasColumnName("VideoHeight");

                            b1.Property<int?>("Width")
                                .HasColumnType("int")
                                .HasColumnName("VideoWidth");

                            b1.HasKey("CarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.Navigation("VideoSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("LteCar.Server.Data.CarChannel", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany("Functions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarTelemetry", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarVideoStream", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany("VideoStreams")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("LteCar.Server.Data.User", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "ActiveVehicle")
                        .WithMany()
                        .HasForeignKey("ActiveVehicleId");

                    b.Navigation("ActiveVehicle");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.HasOne("LteCar.Server.Data.Car", "Car")
                        .WithMany("UserCarSetups")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.User", "User")
                        .WithMany("CarSetups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannel", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserChannelDevice", "UserChannelDevice")
                        .WithMany("Channels")
                        .HasForeignKey("UserChannelDeviceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("UserChannelDevice");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannelDevice", b =>
                {
                    b.HasOne("LteCar.Server.Data.User", "User")
                        .WithMany("UserChannelDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFunctionNodeParameter", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserSetupFunctionNode", "Node")
                        .WithMany("Parameters")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupLink", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserSetupFlowNodeBase", "UserSetupFromNode")
                        .WithMany()
                        .HasForeignKey("UserSetupFromNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserSetupFlowNodeBase", "UserSetupToNode")
                        .WithMany()
                        .HasForeignKey("UserSetupToNodeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("UserSetupFromNode");

                    b.Navigation("UserSetupToNode");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetry", b =>
                {
                    b.HasOne("LteCar.Server.Data.CarTelemetry", "CarTelemetry")
                        .WithMany()
                        .HasForeignKey("CarTelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany()
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarTelemetry");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupCarChannelNode", b =>
                {
                    b.HasOne("LteCar.Server.Data.CarChannel", "CarChannel")
                        .WithMany("SetupNodes")
                        .HasForeignKey("CarChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany()
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarChannel");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFunctionNode", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany()
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupTelemetryNode", b =>
                {
                    b.HasOne("LteCar.Server.Data.CarTelemetry", "Telemetry")
                        .WithMany()
                        .HasForeignKey("TelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany("TelemetryNodes")
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telemetry");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupUserChannelNode", b =>
                {
                    b.HasOne("LteCar.Server.Data.UserChannel", "UserChannel")
                        .WithMany("SetupNodes")
                        .HasForeignKey("UserChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LteCar.Server.Data.UserCarSetup", "UserSetup")
                        .WithMany()
                        .HasForeignKey("UserSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserChannel");

                    b.Navigation("UserSetup");
                });

            modelBuilder.Entity("LteCar.Server.Data.Car", b =>
                {
                    b.Navigation("Functions");

                    b.Navigation("UserCarSetups");

                    b.Navigation("VideoStreams");
                });

            modelBuilder.Entity("LteCar.Server.Data.CarChannel", b =>
                {
                    b.Navigation("SetupNodes");
                });

            modelBuilder.Entity("LteCar.Server.Data.User", b =>
                {
                    b.Navigation("CarSetups");

                    b.Navigation("UserChannelDevices");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserCarSetup", b =>
                {
                    b.Navigation("TelemetryNodes");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannel", b =>
                {
                    b.Navigation("SetupNodes");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserChannelDevice", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("LteCar.Server.Data.UserSetupFunctionNode", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
